config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks

  # # index
  # get 'tasks', to: 'tasks#index', as: :tasks

  # # new
  # get 'tasks/new', to: 'tasks#new', as: :new_task
  # # create
  # post 'tasks', to: 'tasks#create'

  # # show
  # get 'tasks/:id', to: 'tasks#show', as: :task

  # # edit
  # get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  # # update
  # patch 'tasks/:id/update', to: 'tasks#update'

  # # destroy
  # delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # CRUD
  # list all tasks
  def index
    @tasks = Task.all
  end
  # view details of a specific task
  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end
  # add a task
  def create
    # task = Task.create(task_params)
    # task.save
    # redirect_to tasks_path
    Task.create(task_params)
    redirect_to tasks_path
  end
  # edit a task
  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end
  # remove a task
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostRailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit/Update your Tasks</h1>

<%= form_for @task do |f| %>
  <%= f.label :title, "Enter a Title"  %>
  <%= f.text_field :title %>

  <%= f.label :details, "Task Details?" %>
  <%= f.text_field :details %>

  <% unless f.object.new_record? %>
    <div class="checkbox">
      <label>
        <%= f.check_box :completed %> Completed
      </label>
    </div>
  <% end %>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/index.html.erb
<h1>All My Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
  <li>
    <% if task.completed %>
      <i class="fa fa-check-square-o"></i>
    <% else %>
      <i class="fa fa-square-o"></i>
    <% end %>
    <%= link_to task.title, task_path(task.id) %>
    <%= link_to "🚫", task_path(task), method: :delete, data: {:confirm => 'Are you sure?'} %>
  </li>
  <% end %>
</ul>

<%= link_to "Add new Task", new_task_path %>

app/views/tasks/new.html.erb
<h1>Let's create a new Task</h1>

<%= form_for @task do |f| %>
  <%= f.label :title, "Enter a Title"  %>
  <%= f.text_field :title %>

  <%= f.label :details, "Task Details?" %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>Tasks</h1>
<h3> <%= @task.details %> </h3>

<%= link_to "Edit Task",  edit_task_url%>
<%= link_to "Back to All Tasks", tasks_path %>